name: Maximilian Benjamin
favicon: null
layout_spectrum: 0.781188876600936
typography_spectrum: 0.4485120784956962
title: Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#c6c7c1'
    - '#151513'
    - '#434446'
    - '#666e71'
  brandStrength: 0.9375
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
